# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# All the paths relating to the ansible_env.HOME means that this file always points at stuff absolutely
#  in my home directory. This allows me to su to root while having my standard dot files.

if [ "$(uname)" != 'Darwin' ]; then
	# Export the python pip local install bin path
	export PATH="$PATH:{{ ansible_env.HOME }}/.local/bin" # python bin

	export PYTHONPATH="$PYTHONPATH:{{ ansible_env.HOME }}/.local/lib/python2.6/site-packages"

	# Start the powerline daemon if required
	{{ ansible_env.HOME }}/.local/bin/powerline-daemon -q
else
	# Start the powerline daemon if required
	/usr/local/bin/powerline-daemon -q
fi

# Include my custom shell functions
[ -f {{ ansible_env.HOME }}/.shell_functions ] && source {{ ansible_env.HOME }}/.shell_functions

# SU keeping my session info
alias su="su -c \"export ZDOTDIR={{ ansible_env.HOME }} && zsh\""

# "real" SU
alias rsu="/bin/su"

# Alias VIM to always start with my vimrc
alias vim="vim -u {{ ansible_env.HOME }}/.vimrc"

[ -f {{ ansible_env.HOME }}/.machine_rc ] && source {{ ansible_env.HOME }}/.machine_rc

# If we have a running tmux session, attach to it, otherwise stay out of tmux
if [[ -z "$TMUX" && -z "$EMACS" && -z "$VIM" ]] && \
   [[ -n "$SSH_TTY" ]] && \
   tmux has-session 2> /dev/null; then

   exec tmux attach
fi