---

- name: ensure ~/local/bin exists
  file:
    path: "{{ ansible_env.HOME }}/local/bin"
    state: directory
    mode: 0755
  tags:
    - tmux
    - prezto

- name: ensure ~/local/tmp exists
  file:
    path: "{{ ansible_env.HOME }}/local/tmp"
    state: directory
    mode: 0755
  tags:
    - tmux
    - prezto


- name: ensure prezto is installed if ZSH is present
  include: prezto.yml
  tags: prezto

- name: ensure shell facts are set
  include: shell.yml
  tags: powerline

- name: ensure powerline tasks are run
  include: powerline.yml
  tags: powerline

- name: ensure vim tasks are run
  include: vim.yml
  tags: vim

- name: ensure tmux tasks are run
  include: tmux.yml
  tags: tmux

- name: ensure global .gitignore is copied
  copy:
    src: gitignore
    dest: ~/.gitignore
    mode: 0644
  tags: git

- name: ensure global .gitconfig is copied
  copy:
    src: gitconfig
    dest: ~/.gitconfig
    mode: 0644
  tags: git

- name: ensure MacOS specific tasks are run
  include: macos.yml
  tags: macos
  when: ansible_distribution == 'MacOSX'
