---

- name: ensure the powerline folder is owned by me
  file:
    path: ~/.config/powerline
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0775

- name: check to see if pip is already installed.
  command: "pip --version"
  ignore_errors: true
  changed_when: false # read-only task
  always_run: true # for check mode
  register: pip_is_installed

- name: ensure pip is installed
  easy_install:
    name: pip
    state: present
  when: pip_is_installed.rc != 0

- name: check if powerline is locally installed
  stat:
    path: "{{ ansible_env.HOME }}/.local/bin/powerline"
  changed_when: false # read-only task
  always_run: true # for check mode
  register: powerline_installed

- name: ensure powerline is installed
  pip:
    name: powerline-status
    extra_args: '--ignore-installed --upgrade --user' # upgrade/ignore-installed forces it always into the user directory
    state: present
  when: powerline_installed.stat.exists == False

- name: check if argparse is locally installed
  stat:
    path: "{{ ansible_env.HOME }}/.local/lib/python2.6/site-packages/argparse.py"
  changed_when: false # read-only task
  always_run: true # for check mode
  register: argparse_installed

- name: ensure powerline dependancy argparse is installed
  pip:
    name: "argparse"
    extra_args: '--ignore-installed --upgrade --user'
    state: present
  when: argparse_installed.stat.exists == False

- name: ensure the powerline config file is present
  copy:
    src: powerline-config.json
    dest: "{{ ansible_env.HOME }}/.config/powerline/config.json"
    owner: "{{ ansible_user_id }}"
    mode: 0664