---
- name: Set python version for MacOS
  set_fact:
    vim_python_command: python3
  when: ansible_distribution == 'MacOSX'

- name: ensure vimrc is present
  template:
    src: vimrc
    dest: ~/.vimrc
    mode: 0644

- name: ensure the .vim folder is owned by me
  file:
    path: ~/.vim
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0775