---

- name: ensure vimrc is present
  copy:
    src: vimrc
    dest: ~/.vimrc
    mode: 0644

- name: ensure the .vim folder is owned by me
  file:
    path: ~/.vim
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0775